export const t = (lang) => {
    if (lang == 'ru') {
        return {
            Editprofile: "Редактировать профиль",
            Edit: "Edit",
            Deletepost: "Удалить пост",
            search: "поиск",
            Notfound: "Не найдено",
            subscribe: "подписаться",
            Unsubscribe: "Отписаться",
            Youhavenomessages: "У вас нет сообщений",
            Newpublication: "Новая публикация",
            adddescription: "Добавить описание",
            Addphoto: "Добавить фото",
            noPublications: "нет публикаций",
            Bookmarklistisempty: 'Список закладок пуст',
            Album: 'Альбом',
            Information: 'Информация',
            Publications: 'Публикаций',
            Subscribers: 'Подписчиков',
            Nosubscribers: 'Нет подписчиков',
            Subscriptions: 'Подписок',
            Nosubscriptions: 'Нет подписок',
            Bookmarks: 'Закладки',
            logOut: 'Выйти',
            Blacklist: 'Черный список',
            Accountsettings: 'Параметры аккаунта',
            Addinformation: "Доп. информация",
            City: 'Город',
            DateofBirth: 'Дата рождения',
            gender: 'Пол',
            ProfessionFieldofactivity: "Профессия/Сфера деятельности",
            Placeofwork: "Место работы",
            Website: 'Сайт',
            Mail: 'Почта',
            Phonenumber: 'Phone number',
            Brieflyaboutyourself: 'Кратко о себе',
            Day: 'День',
            Month: 'Месяц',
            Year: 'Год',
            Male: 'Мужской',
            Female: 'Женский',
            Changepassword: 'Изменить пароль',
            Changemail: 'Изменить почту',
            OldPassword: 'Старый пароль',
            NewPassword: "Новый пароль",
            repeatnewpassword: 'Повторите новый пароль',
            Confirm: 'Подтвердить',
            password: 'пароль',
            intoablacklist: 'в черный список',
            Blacklistisempty: "Черный список пуст",
            Login: 'Вход',
            Enteryouremail: 'Введите е-майл',
            enterpassword: 'Введите пароль',
            Forgotpassword: 'Забыли пароль?',
            Registration: 'Регистрация',
            Savepassword: 'Сохранить пароль',
            Createapassword: 'Придумайте пароль',
            Repeatpassword: 'Повторите пароль',
            Passwordrecovery: 'Восстановление пароля',
            Enteremailmail: 'Введите эл. почту',
            Next: 'далее',
            Comeupwithanicknam: 'Придумайте никнейм',
            Enteryouremail: 'Укажите почту',
            FirstnameLastnameorchannelname: 'Имя Фамилия или название канала'
        }
    }
    else {
        return {
            Editprofile: "Edit profile",
            Edit: "Edit",
            Deletepost: "Delete post",
            search: "search",
            Notfound: "Not found",
            subscribe: "subscribe",
            Unsubscribe: "Отписаться",
            Youhavenomessages: "You have no messages",
            Newpublication: "New publication",
            adddescription: "add description",
            Addphoto: "Add photo",
            noPublications: "no publications",
            Bookmarklistisempty: 'Bookmark list is empty',
            Album: 'Album',
            Information: 'Information',
            Publications: 'Publications',
            Subscribers: 'Subscribers',
            Nosubscribers: 'No subscribers',
            Subscriptions: 'Subscriptions',
            Nosubscriptions: 'No subscriptions',
            Bookmarks: 'Bookmarks',
            logOut: 'Log Out',
            Blacklist: 'Black list',
            Accountsettings: 'Account settings',
            Addinformation: "Add. information",
            City: 'City',
            DateofBirth: 'Date of Birth',
            gender: 'gender',
            ProfessionFieldofactivity: "Profession/Field of activity",
            Placeofwork: "Place of work",
            Website: 'Website',
            Mail: 'Mail',
            Phonenumber: 'Phone number',
            Brieflyaboutyourself: 'Briefly about yourself',
            Day: 'Day',
            Month: 'Month',
            Year: 'Year',
            Male: 'Male',
            Female: 'Female',
            Changepassword: 'Change password',
            Changemail: 'Change mail',
            OldPassword: 'Old Password',
            NewPassword: "New Password",
            repeatnewpassword: 'repeat new password',
            Confirm: 'Confirm',
            password: 'password',
            intoablacklist: 'into a black list',
            Blacklistisempty: "Blacklist is empty",
            Login: 'Login',
            Enteryouremail: 'Enter your email',
            enterpassword: 'Enter password',
            Forgotpassword: 'Forgot password?',
            Registration: 'Registration',
            Savepassword: 'Save password',
            Createapassword: 'Create a password',
            Repeatpassword: 'Repeat password',
            Passwordrecovery: 'Password recovery',
            Enteremailmail: 'Enter email',
            Next: 'Next',
            Comeupwithanicknam: 'Come up with a nickname',
            Enteryouremail: 'Enter your email',
            FirstnameLastnameorchannelname: 'First name Last name or channel name'
        }
    }
}